{% set version = '0.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-debugr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/debugr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/debugr/debugr_{{ version }}.tar.gz
  sha256: 96f5086952695f10d5c71ae52e0c3e4cf63ff3ae6dd08d4a01a0ad088106d851

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rprojroot
    - r-rstudioapi
  run:
    - r-base
    - r-rprojroot
    - r-rstudioapi

test:
  commands:
    - $R -e "library('debugr')"           # [not win]
    - "\"%R%\" -e \"library('debugr')\""  # [win]

about:
  home: https://github.com/jsugarelli/debugr/
  license: GPL-3.0-only
  summary: Tool to print out the value of R objects/expressions while running an R script. Outputs
    can be made dependent on user-defined conditions/criteria. Debug messages only appear
    when a global option for debugging is set. This way, 'debugr' code can even remain
    in the debugged code for later use without any negative effects during normal runtime.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: debugr
# Title: Debug Tool to Watch Objects/Expressions While Running an R Script
# Version: 0.0.1
# Authors@R: person("Joachim", "Zuckarelli", email = "joachim@zuckarelli.de", role = c("aut", "cre"))
# Maintainer: Joachim Zuckarelli <joachim@zuckarelli.de>
# Description: Tool to print out the value of R objects/expressions while running an R script. Outputs can be made dependent on user-defined conditions/criteria. Debug messages only appear when a global option for debugging is set. This way, 'debugr' code can even remain in the debugged code for later use without any negative effects during normal runtime.
# BugReports: https://github.com/jsugarelli/debugr/issues
# URL: https://github.com/jsugarelli/debugr/
# Depends: R (>= 3.5.0)
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# Imports: utils, rprojroot, rstudioapi
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-07-25 19:46:41 UTC; Joachim
# Author: Joachim Zuckarelli [aut, cre]
# Repository: CRAN
# Date/Publication: 2018-07-30 11:50:03 UTC
